# # Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
# ---
# kind: Secret
# apiVersion: v1
# metadata:
#   name: docker-config-secret
# data:
#   .dockerconfigjson: >-
#     ewoJImF1dGhzIjogewoJCSJnaXRsYWIucHJha3Rpa3VtLXNlcnZpY2VzLnJ1IjogewoJCQkiYXV0aCI6ICJjM1JrTFRBeU9TMHlOanBoV0ZOa05EazJlUT09IgoJCX0sCgkJImdpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6IHsKCQkJImF1dGgiOiAiYzNSa0xUQXlPUzB5TmpwaFdGTmtORGsyZVE9PSIKCQl9Cgl9Cn0=
# type: kubernetes.io/dockerconfigjson