# Секрет, необходимый, чтобы соединяться с Vault и получать креды для БД:
---
apiVersion: v1
kind: Secret
metadata:
  name: vault
  labels:
    app: vault
data:
  vault_token: YUhSMGNEb3ZMM04wWkMwd01qa3RNall1Y0hKaGEzUnBhM1Z0TFhObGNuWnBZMlZ6TG5SbFkyZzZPREl3TUFvPQo=
  vault_host: aHR0cDovL3N0ZC0wMjktMjYucHJha3Rpa3VtLXNlcnZpY2VzLnRlY2g6ODIwMAo=
type: Opaque

# Секрет, необходимый, чтобы соединяться с PostgresSQL
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres
  labels:
    app: postgres
data:
  psql_user: c3RkLTAyOS0yNg==
  psql_password: VGVzdHVzcjEyMzQ=
  psql_url: amRiYzpwb3N0Z3Jlc3FsOi8vcmMxYS0yY2VydHh3ZmI2MHRraHpvLm1kYi55YW5kZXhjbG91ZC5uZXQ6NjQzMi9zdGQtMDI5LTI2P3NzbD10cnVlJnNzbHJvb3RjZXJ0PS9hcHAvWWFuZGV4SW50ZXJuYWxSb290Q0EuY3J0Cg==
type: Opaque

# Секрет, необходимый, чтобы взаимодействовать с докер-реджистри в Гитлабе:
---
kind: Secret
apiVersion: v1
metadata:
  name: docker-config-secret
data:
  .dockerconfigjson: >-
    eyJhdXRocyI6eyJodHRwczovL2dpdGxhYi5wcmFrdGlrdW0tc2VydmljZXMucnU6NTA1MCI6eyJ1c2VybmFtZSI6InNhdXNhZ2Utc3RvcmUiLCJwYXNzd29yZCI6ImhqeFJmM25GMUZVQl9iazljWWJHIiwiYXV0aCI6ImMyRjFjMkZuWlMxemRHOXlaVHBvYW5oU1pqTnVSakZHVlVKZlltczVZMWxpUnc9PSJ9fX0=
type: kubernetes.io/dockerconfigjson