---

- name: Update apt
  apt:
    upgrade: yes
    update_cache: yes

- name: Install Java using Ansible 
  become: true
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python
      - python3-pip
      - python3
      - openjdk-16-jdk

- name: install the lxml package 
  pip:
    name: lxml
    state: latest

- name: Add service user for backend
  user:
    name: "{{ backend_user }}"
    create_home: no
    shell: /sbin/nologin

- name: Create directory
  file:
    path: "{{ backend_path }}/log"
    state: directory

- name: Download artifact from Nexus
  maven_artifact:
    dest: "{{ backend_path }}"
    repository_url: "{{ nexus_url }}-backend/"
    group_id: "com.yandex.practicum.devops"
    artifact_id: "sausage-store-backend"
    version: "{{ backend_version }}"
    username: "{{ nexus_user }}"
    password: "{{ nexus_password }}"

- name: Add permissions
  ansible.builtin.file:
    path: "{{ backend_path }}sausage-store-backend.jar"
    owner: "{{ backend_user }}"
    group: "{{ backend_user }}"
    mode: '0777'

- name: Copy unit-file to server
  template:
    src: sausage-store-backend.service.j2
    dest: /etc/systemd/system/sausage-store-backend.service
  notify: 
    - Reload systemd 
    - Restart backend
  tags: ['copy-template']

...